# Generated by Django 2.1.5 on 2020-04-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_price',
            field=models.IntegerField(default=0),
        ),
    ]
