# Generated by Django 2.1.5 on 2020-05-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_product_max_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(default='', max_length=5000)),
                ('amount', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=90)),
                ('email', models.CharField(default='', max_length=111)),
                ('address', models.CharField(default='', max_length=111)),
                ('city', models.CharField(default='', max_length=111)),
                ('state', models.CharField(default='', max_length=111)),
                ('zip_code', models.CharField(default='', max_length=111)),
                ('contact', models.CharField(default='', max_length=111)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='store/images'),
        ),
    ]
